### ISSUE TITLE
Can not launch after IOS 14

### ISSUE THREAD

**Issue by Hellomik2002** [tanersener/flutter-ffmpeg#205]
<img width="1247" alt="Screen Shot 2020-09-18 at 17 07 56" src="https://user-images.githubusercontent.com/30003495/93594888-7cc8ad80-f9d8-11ea-934e-6cdde82f4195.png">
I found error in XCODE

FLUTTER output:
```
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro.

#0      throwToolExit  (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand  (package:flutter_tools/src/commands/run.dart:458:9)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand  (package:flutter_tools/src/runner/flutter_command.dart:860:18)
#3      _rootRunUnary  (dart:async/zone.dart:1198:47)
#4      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
#5      _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)
#6      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)
#7      Future._propagateToListeners  (dart:async/future_impl.dart:725:32)
#8      Future._completeWithValue  (dart:async/future_impl.dart:529:5)
#9      _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:40:15)
#10     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:311:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary  (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners  (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue  (dart:async/future_impl.dart:529:5)
#18     Future._asyncCompleteWithValue.<anonymous closure>  (dart:async/future_impl.dart:567:7)
#19     _rootRun  (dart:async/zone.dart:1190:13)
#20     _CustomZone.run  (dart:async/zone.dart:1093:19)
#21     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)
#23     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback  (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:169:5)
```

PODFILE:
```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

pubspec:
```
name: ...
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.16+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_translation: 0.17.10+1
  provider: 4.1.3
  cupertino_icons: ^0.1.3
  flutter_svg: 0.18.0
  firebase_auth: 0.18.0+1
  platform_action_sheet: ^0.0.3
  flutter_slidable: 0.5.4
  cloud_firestore: 0.14.0+2
  firebase_storage: 4.0.0
  firebase_messaging: 7.0.0
  shared_preferences: 0.5.8
  intl: 0.16.1
  image_picker: 0.6.7+4
  url_launcher: 5.5.0
  flutter_image: 3.0.0
  firebase_core: 0.5.0
  image_cropper: 1.3.1
  flutter_ffmpeg: 0.2.10
  path: 1.7.0
  path_provider: 1.6.14
  video_thumbnail: 0.2.2
  video_player: 0.10.12+2
  # flutter_video_compress: 0.3.7+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

#   flutter_launcher_icons: "^0.7.3"

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/svgs/settings/
    - assets/images/
    - lib/utils/lang/ar.json
    - lib/utils/lang/en.json
    - lib/utils/lang/ru.json
    - lib/utils/lang/tr.json

  fonts:
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko/Teko-Bold.ttf
        - asset: assets/fonts/Teko/Teko-Light.ttf
        - asset: assets/fonts/Teko/Teko-Medium.ttf
        - asset: assets/fonts/Teko/Teko-Regular.ttf
        - asset: assets/fonts/Teko/Teko-SemiBold.ttf
          style: normal
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SfPro/SFProDisplay-Regular.ttf
          style: normal
```
