### ISSUE TITLE
-i "concat:${names}" -acodec copy -vcodec copy -absf aac_adtstoasc out.mp4. crash

### ISSUE THREAD

**Issue by SinoMiles** [tanersener/flutter-ffmpeg#305]
### **run this command the app will crash.**

```
import 'dart:io';

import 'package:ajanuw_http/ajanuw_http.dart';
import 'package:flutter/material.dart';
import 'package:flutter_ffmpeg/completed_ffmpeg_execution.dart';
import 'package:flutter_ffmpeg/flutter_ffmpeg.dart';
import 'package:flutter_hls_parser/flutter_hls_parser.dart';
import 'package:path_provider/path_provider.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  Future<String> get _localPath async {
    final directory = await getApplicationDocumentsDirectory();
    return directory.path;
  }

  var list = [];
  Directory save;
  download() async {
    Uri playlistUri;
    List<String> lines;
    var playList;

    try {
      var api = AjanuwHttp();
      var url =
          "https://pcvideohwyunott.titan.mgtv.com/c1/2021/03/29_0/A7EBDDE9A9BFAA7DEF3D5E5FE46B898A_20210329_1_1_1815_mp4/D9E37862323F5338CE8F4DAF0013BF36.m3u8?arange=0&pm=qNzhCX6drB~6pl~s45cmvIbAgbr8W3svbm_BLsUM17SOGk9XkuiJkn6KiMoWeft~EjoDqyb2~r9Mhr9TYb6yFNIdwn6bGUGaN~gYKswtM2nSIGWM~pgKjEjFSeS41hZ_iHjIQ2FwyYSLqoV0~EIZnLgmVLx5E549TVri3bS7vlC2lxtyYifl1qp0GZEwUR_ijjm2sZdnZmCYPjYhNbBKat9IytvPqBGestv00DKRJFoLDS0t93Kie2qUxLGckUKNtaDfYaF5up_t3YKQMiGHMZekZubKcV8AOgPJi_NXcM5fQmvA1xD_15trXxzC32IFwPD3QyS6EKaeq7_WgWtDMXhdklcBJmd5iK2XJqywku48eVT~Tg2beu4QTTp3C4BZd8EljaqiE19MTkuUj5PNlz9l0OmWhC~SP02nkKJAko079cBnxeQwks1iVsDWi5kniZp~T9LFobQ24tpYkBMEqM4JJYygvRit4JJEGWXYlzgkTCUj&mr=l0yDpEzmWn9lSqiGp1uCZKyafT914c4uEhY~cenmDMOFSkwC1UOldMbo2BWRlqwdaOw7NcLay80-&vcdn=0&scid=25065&cpno=6k14ls&ruid=58a2d9f894a146fd&ld=sdkbytelog02_sdkbytelog02&_t=1620886288625&parwix";
      var r = await api.get(url);
      playList =
          await HlsPlaylistParser.create().parseString(playlistUri, r.body);
      if (playList is HlsMasterPlaylist) {
        // master m3u8 file
      } else if (playList is HlsMediaPlaylist) {
        // media m3u8 file
        for (var item in playList.segments) {
          final path = await _localPath;
          var splitList = item.url.split('?');
          var currentName = splitList[0];
          var savePath = Directory("$path/download/");
          bool exists = await savePath.exists();

          if (!exists) {
            await savePath.create();
            save = savePath;
          } else {
            save = savePath;
          }
          var file = File(savePath.path + currentName);
          var body = (await api.get(
                  'https://pcvideohwyunott.titan.mgtv.com/c1/2021/03/29_0/A7EBDDE9A9BFAA7DEF3D5E5FE46B898A_20210329_1_1_1815_mp4/' +
                      item.url))
              .bodyBytes;
          file.writeAsBytesSync(body);
          print(file.path);
          list.add(currentName);
        }
      }
    } on ParserException catch (e) {
      print(e);
    }
  }

  convert() {
    var names = '';

    for (var i = 0; i < list.length; i++) {
      if (i == list.length - 1) {
        names = names + list[i];
      } else {
        names = names + list[i] + "|";
      }
    }
    Directory.current = save;
    var s = Directory.current.listSync();
    print(s);
    FlutterFFmpeg fFmpeg = FlutterFFmpeg();

    var command =
        '-i "concat:${names}" -acodec copy -vcodec copy -absf aac_adtstoasc out.mp4';
    fFmpeg.executeAsync(command, (CompletedFFmpegExecution execution) {
      print(
          "FFmpeg process for executionId ${execution.executionId} exited with rc ${execution.returnCode}");
    }).then((executionId) =>
        print("Async FFmpeg process started with executionId $executionId."));
  }

  @override
  void initState() {
    // download();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
                onPressed: () {
                  download();
                },
                child: Text('down')),
            ElevatedButton(
                onPressed: () {
                  convert();
                },
                child: Text('convert')),
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
// This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

```
name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hls_parser: ^2.0.0
  ajanuw_http: ^0.6.0
  path_provider: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter_ffmpeg: ^0.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
