### ISSUE TITLE
Package dependency flutter_ffmpeg is a git dependency, this not allowed in published packages.

### ISSUE THREAD

**Issue by thejacer87** [tanersener/flutter-ffmpeg#52]
**Description**
I'm building a package that requires the `audio_lts` package:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_ffmpeg:
    git:
      url: git://github.com/tanersener/flutter-ffmpeg.git
      ref: v0.2.6
      path: packages/flutter_ffmpeg_audio_lts
```

But when I try to publish it, it fails saying: `Package dependency flutter_ffmpeg is a git dependency, this not allowed in published packages.`

**Expected behavior**
Custom flutter package gets published when depending on a specific package

**Current behavior**
Publishing package using 'flutter pub' failed because you can't depend on git source.

**Screenshots**
![image](https://user-images.githubusercontent.com/6412919/61607933-bf8ccb00-ac05-11e9-9c71-b45b360d4562.png)

**Environment**
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale en_CA.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (2 available)

• No issues found!
```

**Other**
Just trying to require the `audio_lts` and not the main package.

Edit: as expected, if i require the main package, my build fails because of the sdk version mismatch:
` Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 24 declared in library [:flutter_ffmpeg]`
