### ISSUE TITLE
[iOS] v0.2.9 release fails with MissingPluginException

### ISSUE THREAD

**Issue by tanersener** [tanersener/flutter-ffmpeg#94]
`iOS` release fails with the following exception.

```
flutter: Loading flutter-ffmpeg.
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following MissingPluginException was thrown while activating platform stream on channel
flutter: flutter_ffmpeg_event:                                          
flutter: MissingPluginException(No implementation found for method listen on channel flutter_ffmpeg_event)
flutter:                                                                
```

**Comment by tanersener** [comment]
The following declaration in `pubspec.yaml` is causing this failure.

```
flutter:
  plugin:
    android:
      package: com.arthenica.flutter.ffmpeg
      pluginClass: FlutterFFmpegPlugin
    ios:
      pluginClass: FlutterFFmpegPlugin
```

That section needs to be updated as the following.

```
flutter:
  plugin:
    platforms:
      android:
        package: com.arthenica.flutter.ffmpeg
        pluginClass: FlutterFFmpegPlugin
      ios:
        pluginClass: FlutterFFmpegPlugin
```
